version: "3.7"

services:
  postgres:
    image: postgres:9.6
    volumes:
      - ./etc/postgres:/docker-entrypoint-initdb.d:z
    ports:
      - "5432:5432"
    expose:
      - "5432"
    environment:
      POSTGRES_USER: luxor
      POSTGRES_PASSWORD: luxor
      POSTGRES_DB: luxor
    restart: on-failure

  stratum:
    depends_on:
      - postgres
    build:
      context: .
      dockerfile: Dockerfile
    container_name: stratum
    ports:
      - "4000:4000"
    env_file:
      - .env
    restart: on-failure

networks:
  miner:
