// Code generated by mockery v2.7.4. DO NOT EDIT.

package mocks

import (
	entity "github.com/ednailson/miner/internal/domain/entity"
	mock "github.com/stretchr/testify/mock"
)

// Miner is an autogenerated mock type for the Miner type
type Miner struct {
	mock.Mock
}

// Save provides a mock function with given fields: req
func (_m *Miner) Save(req entity.Request) interface{} {
	ret := _m.Called(req)

	var r0 interface{}
	if rf, ok := ret.Get(0).(func(entity.Request) interface{}); ok {
		r0 = rf(req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	return r0
}
